django/wire/base/urls.py
from django.urls import path

from . import views
from django.views.generic import TemplateView
from .views import HomeView

app_name = 'base'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login', TemplateView.as_view(template_name='base/login.html'), name='login'),
    path('signup', TemplateView.as_view(template_name='base/signup.html'), name='signup'),
    path('register', views.register, name='register'),
    path('verify', views.verify_user, name='verify'),
    path('logout', views.log_out, name='logout'),
    path('get-recommended-users/<path:excluded_username>', views.recommended_users, name='recommended_users')
]

django/wire/wire/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('base.urls')),
    url(r'^', include('wire_profile.urls')),
]

admin.site.site_header = 'Wire Administration'
admin.site.site_title = 'Wire'

django/wire/wire_profile/urls.py
from django.urls import path

from . import views
from django.views.generic import TemplateView
from .views import ProfileView, CurrentProfileView, SearchView, SearchMessageView, SearchUserView

app_name = 'wire_profile'
urlpatterns = [
    path('profile/<path:username>', ProfileView.as_view(), name='profile'),
    path('profile/', CurrentProfileView.as_view(), name='current_profile'),
    path('message/<path:username>', views.get_messages, name='get_message'),
    path('messages/<path:user_ids>', views.get_messages_by_ids, name='get_messages_by_ids'),
    path('message/', views.create_message, name='message'),
    path('follow/<path:username>', views.follow_user, name='follow_user'),
    path('followers/<path:username>', views.get_followers, name='get_followers'),
    path('following/<path:username>', views.get_following, name='get_following'),
    path('users/<path:user_ids>', views.get_user_ids, name='get_user_ids'),
    path('user/id/<int:user_id>', views.get_user_id, name='get_user_id'),
    path('search', SearchView.as_view(), name='search'),
    path('search/wire/<path:query>', SearchMessageView.as_view(), name='search_message'),
    path('search/user/<path:query>', SearchUserView.as_view(), name='search_user'),
]

django/wire/wire_profile/models.py
from django.db import models
from django.contrib.auth.models import User


class Message(models.Model):
    message_text = models.CharField(max_length=280)
    created = models.DateTimeField('created')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.message_text


class Follow(models.Model):
    follower_id = models.ForeignKey(User, related_name='follower_user', on_delete=models.CASCADE)
    following_id = models.ForeignKey(User, related_name='followed_user', on_delete=models.CASCADE)

django/wire/wire_profile/forms.py
from django import forms


class NewWireForm(forms.Form):
    message = forms.CharField(widget=forms.Textarea(attrs={'rows': '3', 'cols': '40'}), label='Message', max_length=280)


class SearchForm(forms.Form):
    search_choices = (
        ('true', 'Wires'),
        ('false', 'Users')
    )
    search_query = forms.CharField(label='Search Query')
    is_wire_search = forms.CharField(widget=forms.Select(choices=search_choices), label='Search For?')

django/wire/wire_profile/views.py
from django.shortcuts import render
from django.template.loader import get_template
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.views.generic import TemplateView
from django.contrib.auth.models import User
from django.contrib import messages
from django.utils import timezone
from django.db import DatabaseError
from django.db.models import ObjectDoesNotExist, FieldDoesNotExist
from django.core import serializers
from .forms import NewWireForm, SearchForm
from .models import Message, Follow

# Create your views here.


class ProfileView(TemplateView):
    template_name = "wire_profile/profile.html"

    def get(self, request, *args, **kwargs):
        """
        Get the profile page of the given user. Show the search page if the user was not found

        :param request: The current request
        :param args: sent to parent method
        :param kwargs: sent to parent method
        :return: Either redirect to the search page or render the profile page
        """
        username = self.kwargs['username'].rstrip('/')
        context = self.get_context_data(**kwargs)
        context['is_current_user'] = False

        try:
            user = User.objects.get(username=username)
            context['user'] = user
            return self.render_to_response(context)

        except (ObjectDoesNotExist, FieldDoesNotExist):
            messages.error(request, 'The requested user was not found', extra_tags='danger')
            url = reverse('wire_profile:search_user', kwargs={'query': username})
            return HttpResponseRedirect(url)


class CurrentProfileView(TemplateView):
    template_name = "wire_profile/current_profile.html"

    def get(self, request, *args, **kwargs):
        """
        Get the current profile if the user is logged in.

        :param request: The current request
        :param args: sent to parent method
        :param kwargs: sent to parent method
        :return: Either redirect to the search page or render the profile page
        """
        if request.user.is_authenticated:
            context = self.get_context_data(**kwargs)
            form = NewWireForm()
            context['form'] = form
            context['user'] = request.user
            return self.render_to_response(context)
        else:
            messages.error(request, 'You must log in to view your profile page', extra_tags='danger')
            return HttpResponseRedirect(reverse('base:home'))


class SearchView(TemplateView):
    template_name = 'wire_profile/search.html'

    def get(self, request, *args, **kwargs):
        """
        Render the search page

        :param request: The current request
        :param args: sent to parent method
        :param kwargs: sent to parent method
        :return: Render the search page
        """
        context = self.get_context_data(**kwargs)
        context['form'] = SearchForm()
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        form = SearchForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['is_wire_search'] == 'true':
                url = reverse('wire_profile:search_message', kwargs={'query': form.cleaned_data['search_query']})
                return HttpResponseRedirect(url)
            else:
                url = reverse('wire_profile:search_user', kwargs={'query': form.cleaned_data['search_query']})
                return HttpResponseRedirect(url)
        else:
            messages.error(request, 'Please complete the search form', extra_tags='danger')
            context = self.get_context_data(**kwargs)
            context['form'] = SearchForm()
            return self.render_to_response(context)


class SearchMessageView(TemplateView):
    template_name = 'wire_profile/search_message.html'

    def get(self, request, *args, **kwargs):
        """
        Render the matching messages for a search message query

        :param request: The current request
        :param args: sent to parent method
        :param kwargs: sent to parent method
        :return: Render the search message results page
        """
        query = self.kwargs['query']
        search_results = Message.objects.filter(message_text__icontains=query).all()
        context = self.get_context_data(**kwargs)
        context['search_results'] = search_results
        return self.render_to_response(context)


class SearchUserView(TemplateView):
    template_name = 'wire_profile/search_user.html'

    def get(self, request, *args, **kwargs):
        """
        Render the matching messages for a search message query

        :param request: The current request
        :param args: sent to parent method
        :param kwargs: sent to parent method
        :return: Render the search message results page
        """
        query = self.kwargs['query']
        search_results = User.objects.filter(username__icontains=query).all()
        context = self.get_context_data(**kwargs)
        context['search_results'] = search_results
        return self.render_to_response(context)


def create_message(request):
    """
    Create a message for the logged in user

    :param request: The request sent by the user
    :return: Display the profile page with a relevant message
    """
    if request.method == 'POST':
        form = NewWireForm(request.POST)
        if form.is_valid():
            if request.user.is_authenticated:
                message = form.cleaned_data['message']
                try:
                    Message.objects.create(message_text=message, created=timezone.now(), user=request.user)
                    messages.success(request, 'Message created successfully', extra_tags='success')
                    return HttpResponseRedirect(reverse('wire_profile:current_profile'))
                except DatabaseError:
                    messages.error(request, 'Error creating message, please contact support', extra_tags='danger')
                    return HttpResponseRedirect(reverse('wire_profile:current_profile'))
            else:
                messages.error(request, 'Sorry, only registered users can create messages', extra_tags='danger')
                return HttpResponseRedirect(reverse('base:home'))
        else:
            messages.error(request, 'Please enter a message', extra_tags='danger')
            return HttpResponseRedirect(reverse('wire_profile:current_profile'))
    else:
        messages.error(request, 'Sorry, you cannot access that URL', extra_tags='danger')
        return HttpResponseRedirect(reverse('base:home'))


def get_messages(request, username):
    """
    Retrieve messages for the given username in JSON format

    :param request: The request sent by the user
    :param username: The username to retrieve messages for
    :return:
    """
    try:
        user = User.objects.get(username=username)
        user_messages = Message.objects.filter(user=user).order_by('-created').values('message_text', 'created', 'user')
        return JsonResponse(list(user_messages), safe=False)

    except (ObjectDoesNotExist, FieldDoesNotExist):
        messages.error(request, 'The requested user was not found', extra_tags='danger')
        return HttpResponseRedirect(reverse('base:home'))


def get_messages_by_ids(request, user_ids):
    """
    Retrieve messages for the given user ids in JSON format

    :param request: The request sent by the user
    :param user_ids: The user ids to retrieve messages for
    :return:
    """
    try:
        user_ids_list = filter(bool, user_ids.split('/'))
        user_ids_list = list(map(int, user_ids_list))
        users = User.objects.filter(pk__in=user_ids_list)
        user_messages = Message.objects.filter(user__in=users).order_by('-created').values('message_text', 'created', 'user')
        return JsonResponse(list(user_messages), safe=False)

    except (ObjectDoesNotExist, FieldDoesNotExist):
        messages.error(request, 'Error retrieving messages, Please contact support', extra_tags='danger')
        return HttpResponseRedirect(reverse('base:home'))


def follow_user(request, username):
    """
    Follow the given username

    :param request: The request that called this function
    :param username: The user to follow
    :return: success or failure message in JSON format
    """
    username = username.rstrip('/')
    if not request.user.is_authenticated:
        return JsonResponse({'success': False, 'message': 'You must be logged in to follow a user'})
    if request.user.username == username:
        return JsonResponse({'success': False, 'message': 'You cannot follow yourself!'})
    try:
        user = User.objects.get(username=username)
        maybe_following = Follow.objects.filter(follower_id=request.user).filter(following_id=user)
        if maybe_following.count() > 0:
            maybe_following.delete()
            return JsonResponse({'success': True, 'message': 'You have successfully unfollowed ' + username})
        Follow.objects.create(follower_id=request.user, following_id=user)
        return JsonResponse({'success': True, 'message': 'You have successfully followed ' + username})

    except(ObjectDoesNotExist, FieldDoesNotExist):
        return JsonResponse({'success': False, 'message': 'The user you tried to follow was not found'})


def get_followers(request, username):
    """
    Get the users following the given user

    :param request: The request that called this function
    :param username: The user to get the followers for
    :return: list of followers or failure message in JSON format
    """
    try:
        user = User.objects.get(username=username)
        followers = Follow.objects.filter(following_id=user).values('follower_id', 'following_id')
        return JsonResponse(list(followers), safe=False)
    except(ObjectDoesNotExist, FieldDoesNotExist):

django/wire/wire_profile/templates/wire_profile/current_profile.html
{% extends "base/global/base.html" %}

{% load django_bootstrap_breadcrumbs %}
{% load bootstrap3 %}
{% load static %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'profile/profile.css' %}" />
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'profile/current_profile.js'%}"></script>
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Profile" "wire_profile:current_profile" %}
{% endblock %}

{% block title %}
    Your Profile
{% endblock %}

{% block content %}
    <main>
         <!-- The new wire modal -->
        <div id="create-wire-modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Create Wire</h4>
                        <button class="close" type="button" data-dismiss="modal">
                            <span>&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form id="create-wire-form" class="create-wire-form" role=form method=post action="{% url 'wire_profile:message' %}">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                        </form>
                        <div class="modal-footer">
                            <button class="btn btn-default " type="button" data-dismiss="modal">Close</button>
                            <button class="btn btn-primary " type="submit" form="create-wire-form">Submit Wire</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-3 user-info">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <h3>Your Page</h3>
                        </li>
                        <li class="list-group-item">
                            <button class="btn btn-primary create-wire" type="button" data-toggle="modal" data-target="#create-wire-modal">New Wire</button>
                        </li>
                        <li class="list-group-item">
                            <a href="/profile/{{ user.username }}">See how your profile page looks like to others</a>
                        </li>
                    </ul>
                    <ul id="following" class="list-group">
                        <li id="following-header" class="list-group-item">
                            <h3>Following</h3>
                        </li>
                        <li class="list-group-item">
                            <div class="loader"></div>
                        </li>
                    </ul>
                    <ul id="followers" class="list-group">
                        <li id="followers-header" class="list-group-item">
                            <h3>Followers</h3>
                        </li>
                        <li class="list-group-item">
                            <div class="loader"></div>
                        </li>
                    </ul>
                </div>
                <div class="col-sm-6 user-wires">
                    <ul id="messages-list" class="list-group">
                        <li id="messages-header" class="list-group-item">
                            <h3>Your Feed</h3>
                        </li>
                        <li class="list-group-item loader-container">
                            <div class="loader"></div>
                        </li>
                    </ul>
                </div>
                <div id="recommended-users" class="col-sm-3">
                    <ul class="list-group">
                        <li id="recommended-users-header" class="list-group-item">
                            <h3>Other Users</h3>
                        </li>
                        <li class="list-group-item">
                            <div class="loader"></div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </main>

    <script type="text/javascript">
        var jsUsername = '{{ user.username }}';
    </script>
{% endblock %}

django/wire/wire_profile/templates/wire_profile/profile.html
{% extends "base/global/base.html" %}

{% load django_bootstrap_breadcrumbs %}
{% load bootstrap3 %}
{% load static %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'profile/profile.css' %}" />
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'profile/profile.js'%}"></script>
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Profile" "wire_profile:profile" %}
{% endblock %}

{% block title %}
    {{ user.username }}'s Profile
{% endblock %}

{% block content %}
    <main>
        <div class="container">
            <div class="row">
                <div class="col-sm-3 user-info">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <h3>{{user.username}}'s Page</h3>
                        </li>
                    </ul>
                    <ul id="following" class="list-group">
                        <li id="following-header" class="list-group-item">
                            <h3>Following</h3>
                        </li>
                        <li class="list-group-item">
                            <div class="loader"></div>
                        </li>
                    </ul>
                    <ul id="followers" class="list-group">
                        <li id="followers-header" class="list-group-item">
                            <h3>Followers</h3>
                        </li>
                        <li class="list-group-item">
                            <div class="loader"></div>
                        </li>
                    </ul>
                </div>
                <div class="col-sm-6 user-wires">
                    <ul id="messages-list" class="list-group">
                        <li id="messages-header" class="list-group-item">
                            <h3>Wires</h3>
                        </li>
                        <li class="list-group-item loader-container">
                            <div class="loader"></div>
                        </li>
                    </ul>
                </div>
                <div id="recommended-users" class="col-sm-3">
                    <ul class="list-group">
                        <li id="recommended-users-header" class="list-group-item">
                            <h3>Other Users</h3>
                        </li>
                        <li class="list-group-item">
                            <div class="loader"></div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </main>

    <script type="text/javascript">
        var jsUsername = '{{ user.username }}';
    </script>
{% endblock %}

django/wire/wire_profile/templates/wire_profile/search.html
{% extends "base/global/base.html" %}

{% load django_bootstrap_breadcrumbs %}
{% load bootstrap3 %}
{% load static %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Search" "wire_profile:search" %}
{% endblock %}

{% block title %}
    Search
{% endblock %}

{% block content %}
<main>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <form id="search-form" class="inline form-horizontal" role=form method=post action="/search">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

django/wire/wire_profile/templates/wire_profile/search_message.html
{% extends "base/global/base.html" %}

{% load django_bootstrap_breadcrumbs %}
{% load bootstrap3 %}
{% load static %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Search" "wire_profile:search" %}
    {% breadcrumb "Search Message" "wire_profile:search_message" %}
{% endblock %}

{% block title %}
    Wire Search Results
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'profile/search.js'%}"></script>
{% endblock %}

{% block content %}
<main>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>Search Results</h1>
                {% if search_results %}
                    <h3>
                        Wires Found
                    </h3>
                    <ul class="list-group messages-list">
                        {% for result in search_results %}
                            <li class="list-group-item">
                                <h4 class="list-group-item-heading">
                                    {{ result.message_text }}
                                </h4>
                                <p class="list-group-item-text">
                                    Posted on {{ result.created|date:"d/m/Y  G:i" }} at {{ result.created|date:"G:i" }} by <a href="{% url 'wire_profile:profile' username=result.user.username %}">{{result.user.username}}</a>
                                </p>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <h3>No message containing {{query}} found</h3>
                {% endif %}
            </div>
        </div>
    </div>
</main>
{% endblock %}

django/wire/wire_profile/templates/wire_profile/search_user.html
{% extends "base/global/base.html" %}

{% load django_bootstrap_breadcrumbs %}
{% load bootstrap3 %}
{% load static %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Search" "wire_profile:search" %}
    {% breadcrumb "Search Message" "wire_profile:search_message" %}
{% endblock %}

{% block title %}
    User Search Results
{% endblock %}

{% block content %}
<main>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>Search Results</h1>
                {% if search_results %}
                    <h3>
                        Users Found
                    </h3>
                    <ul class="list-group users-list">
                        {% for result in search_results %}
                            <li class="list-group-item">
                                <h4 class="list-group-item-heading">
                                    <a href="{% url 'wire_profile:profile' username=result.username %}">{{result.username}}</a>
                                </h4>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <h3>
                        No user containing {{query}} in their name found
                    </h3>
                    <h4>
                        <a href="{% url 'wire_profile:search' %}">
                            Click here to go back to the search page
                        </a>
                    </h4>
                {% endif %}
            </div>
        </div>
    </div>
</main>
{% endblock %}