django/wire/base/urls.py
from django.urls import path

from . import views
from django.views.generic import TemplateView
from .views import HomeView

app_name = 'base'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login', TemplateView.as_view(template_name='base/login.html'), name='login'),
    path('signup', TemplateView.as_view(template_name='base/signup.html'), name='signup'),
    path('register', views.register, name='register'),
    path('verify', views.verify_user, name='verify'),
    path('logout', views.log_out, name='logout'),
    path('get-recommended-users/<path:excluded_username>', views.recommended_users, name='recommended_users')
]

django/wire/wire/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('base.urls')),
    url(r'^', include('wire_profile.urls')),
]

admin.site.site_header = 'Wire Administration'
admin.site.site_title = 'Wire'

django/wire/wire_profile/urls.py
from django.urls import path

from . import views
from django.views.generic import TemplateView
from .views import ProfileView, CurrentProfileView, SearchView, SearchMessageView, SearchUserView

app_name = 'wire_profile'
urlpatterns = [
    path('profile/<path:username>', ProfileView.as_view(), name='profile'),
    path('profile/', CurrentProfileView.as_view(), name='current_profile'),
    path('message/<path:username>', views.get_messages, name='get_message'),
    path('messages/<path:user_ids>', views.get_messages_by_ids, name='get_messages_by_ids'),
    path('message/', views.create_message, name='message'),
    path('follow/<path:username>', views.follow_user, name='follow_user'),
    path('followers/<path:username>', views.get_followers, name='get_followers'),
    path('following/<path:username>', views.get_following, name='get_following'),
    path('users/<path:user_ids>', views.get_user_ids, name='get_user_ids'),
    path('user/id/<int:user_id>', views.get_user_id, name='get_user_id'),
    path('search', SearchView.as_view(), name='search'),
    path('search/wire/<path:query>', SearchMessageView.as_view(), name='search_message'),
    path('search/user/<path:query>', SearchUserView.as_view(), name='search_user'),
]

django/wire/base/models.py
from django.db import models

django/wire/base/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, Http404, JsonResponse
from django.urls import reverse
from django.views.generic import TemplateView
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.db import IntegrityError, DatabaseError
from django.db.models import ObjectDoesNotExist, FieldDoesNotExist
from django.core.validators import validate_email
from django.core.exceptions import  ValidationError
from wire_profile.models import Follow, Message


class HomeView(TemplateView):
    template_name = 'base/index.html'

    def get(self, request, *args, **kwargs):
        """
        Render the home page, ensuring latest messages and tagged messages are available for use in the template

        :param request: The current request
        :param args: sent to parent method
        :param kwargs: sent to parent method
        :return: Render the search message results page
        """

        latest_messages = Message.objects.order_by('-created').all()[:5]
        latest_tagged_messages = Message.objects.filter(message_text__icontains=' #').order_by('-created').all()[:5]

        context = self.get_context_data(**kwargs)
        context['latest_messages'] = latest_messages
        context['latest_tagged_messages'] = latest_tagged_messages
        return self.render_to_response(context)


def register(request):
    """
    Create a user using the information sent by a POST request. Perform backend validation on the email.
    Handle error messages for invalid email addresses and whether the username has already been taken

    :param request: The current request
    :return: Redirect the user to the appropriate page, with any necessary messages
    """
    username = request.POST.get('username')
    password = request.POST.get('password')
    email = request.POST.get('email')

    """
    Perform some backend validation
    """
    if not username:
        messages.error(request, 'Please enter a username', extra_tags='danger')
    elif len(username) > 150:
        messages.error(request, 'The maximum number of characters for a username is 150', extra_tags='danger')
    if not password:
        messages.error(request, 'Please enter a password', extra_tags='danger')
    if not email:
        messages.error(request, 'Please enter an email address', extra_tags='danger')
    elif len(email) > 254:
        messages.error(request, 'The maximum number of characters for an email address is 254', extra_tags='danger')

    """
    If any of the backend validation has failed, redirect back to the sign in page
    TODO: Add functionality to refill the form with any data the user has input
    """
    if len(messages.get_messages(request)) != 0:
        return HttpResponseRedirect(reverse('base:signup'))

    try:
        validate_email(email)
    except ValidationError:
        messages.error(request, 'Please enter a valid email address', extra_tags='danger')
        return HttpResponseRedirect(reverse('base:signup'))

    try:
        user = User.objects.create_user(username, email, password)
    except IntegrityError:
        messages.error(request, 'That username already exists', extra_tags='danger')
        return HttpResponseRedirect(reverse('base:signup'))
    except ValueError:
        messages.error(request, 'Please ensure you have entered a username, email, and password', extra_tags='danger')
        return HttpResponseRedirect(reverse('base:signup'))
    except DatabaseError:
        messages.error(request, 'Error creating message, please contact support', extra_tags='danger')
        return HttpResponseRedirect(reverse('wire_profile:current_profile'))

    login(request, user)
    messages.success(request, 'Welcome to Wire, ' + user.username)
    return HttpResponseRedirect(reverse('base:home'))


def verify_user(request):
    """
    Validate the username and password provided by the request

    :param request: The request that called this function
    :return: If the username and password is valid, log the user in and redirect to the home page. Else, redirect the
             user to the log in page and show an error message
    """
    username = request.POST.get('username')
    password = request.POST.get('password')

    """
    Perform some backend validation
    """
    if not username:
        messages.error(request, 'Please enter a username', extra_tags='danger')
    elif len(username) > 150:
        messages.error(request, 'The maximum number of characters for a username is 150', extra_tags='danger')
    if not password:
        messages.error(request, 'Please enter a password', extra_tags='danger')

    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        messages.success(request, 'Welcome back, ' + user.username)
        return HttpResponseRedirect(reverse('base:home'))
    else:
        messages.error(request, 'Your username or password is incorrect', extra_tags='danger')
        return HttpResponseRedirect(reverse('base:login'))


def log_out(request):
    """
    Log the user out of the current session

    :param request: The request that called this function
    :return: Log the user out and return to the home page
    """
    logout(request)
    messages.success(request, 'You have logged out successfully')
    return HttpResponseRedirect(reverse('base:home'))


def recommended_users(request, excluded_username):
    """
    Return five users that is not the logged in user, anyone followed by the logged in user, or the specified excluded
    user

    :param request: The request that called this function
    :param excluded_username: A user not to include in the list
    :return: JSON list of users
    """
    try:
        if request.user.is_authenticated:
            follow_query = Follow.objects.filter(follower_id=request.user)
            users = User.objects.filter().exclude(id=request.user.id).exclude(username=excluded_username)\
                .exclude(followed_user__in=follow_query).values('username')[:5]
            return JsonResponse(list(users), safe=False)

        users = User.objects.filter().exclude(username=excluded_username).values('username')[:5]
        return JsonResponse(list(users), safe=False)

    except (ObjectDoesNotExist, FieldDoesNotExist):
        messages.error(request, 'Error retrieving recommended users. Please Contact IT', extra_tags='danger')
        return HttpResponseRedirect(reverse('base:home'))

django/wire/base/templates/base/global/base.html
{% load static %}

{# This is a the base html page. Other pages will populate the content block of this page #}
{# See: https://docs.djangoproject.com/en/2.0/ref/templates/language/#template-inheritance #}

<html lang="en">
    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {% block stylesheets %}
            <link rel="stylesheet" type="text/css" href="{% static 'base/bootstrap/css/bootstrap.min.css' %}" />
            <link rel="stylesheet" type="text/css" href="{% static 'base/global/css/custom.css' %}" />
        {% endblock %}
        <title>{%block title %}Welcome to Wire!{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">Wire</a>
                    <button class="navbar-toggle collapse" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    {# Load urls, allowing you to dynamically set the active url in the navbar #}
                    {# See: https://stackoverflow.com/a/38808910 #}

                    {% url 'base:home' as home %}
                    {% url 'wire_profile:current_profile' as profile %}
                    {% url 'wire_profile:search' as search %}
                    {% url 'base:logout' as logout %}
                    {% url 'base:login' as login %}
                    {% url 'base:signup' as signup %}
                    <ul class="nav navbar-nav">
                        <li class="nav-item{% if request.path == home %} active{%endif%}">
                            <a href="{{ home }}">Home</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item{% if request.path == profile %} active{%endif%}">
                                <a href="{{ profile }}">Profile</a>
                            </li>
                        {% endif %}
                        <li class="nav-item{% if request.path == search %} active{%endif%}">
                            <a href="{{ search }}">Search</a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a href="#">{{ user.username }}</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{ logout }}">Log Out</a>
                            </li>
                        {% else %}
                            <li class="nav-item{% if request.path == login %} active{%endif%}">
                                <a href="{{ login }}">Log In</a>
                            </li>
                            <li class="nav-item{% if request.path == signup %} active{%endif%}">
                                <a href="{{ signup }}">Sign Up</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        {% load django_bootstrap_breadcrumbs %}

        {% block breadcrumbs %}
            {% clear_breadcrumbs %}
            {% breadcrumb "Home" "base:home" %}
        {% endblock %}

        {% block crumbs %}
            {% if request.path != home %}
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12">
                            {% render_breadcrumbs "django_bootstrap_breadcrumbs/bootstrap3.html" %}
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endblock %}

        <div class="container message-container">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible col-sm-12">
                    <a href="#" class="close" data-dismiss="alert">&times;</a>
                    {{ message }}
                </div>
            {% endfor %}
        </div>

        {% block content %}{% endblock %}

        <footer>
            <div class="container">
                <p class="text-muted text-center">Think of a footer</p>
            </div>
        </footer>

        {% block scripts %}
            <script type="text/javascript" src="{% static 'base/jquery/jquery-3.2.1.min.js'%}"></script>
            <script type="text/javascript" src="{% static 'base/bootstrap/js/bootstrap.min.js'%}"></script>
            <script type="text/javascript" src="{% static 'base/global/js/global.js'%}"></script>
        {% endblock %}
    </body>
</html>