django/wire/base/urls.py
from django.urls import path

from . import views
from django.views.generic import TemplateView
from .views import HomeView

app_name = 'base'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login', TemplateView.as_view(template_name='base/login.html'), name='login'),
    path('signup', TemplateView.as_view(template_name='base/signup.html'), name='signup'),
    path('register', views.register, name='register'),
    path('verify', views.verify_user, name='verify'),
    path('logout', views.log_out, name='logout'),
    path('get-recommended-users/<path:excluded_username>', views.recommended_users, name='recommended_users')
]

django/wire/wire/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('base.urls')),
    url(r'^', include('wire_profile.urls')),
]

admin.site.site_header = 'Wire Administration'
admin.site.site_title = 'Wire'

django/wire/base/models.py
from django.db import models

django/wire/base/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, Http404, JsonResponse
from django.urls import reverse
from django.views.generic import TemplateView
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.db import IntegrityError, DatabaseError
from django.db.models import ObjectDoesNotExist, FieldDoesNotExist
from django.core.validators import validate_email
from django.core.exceptions import  ValidationError
from wire_profile.models import Follow, Message


class HomeView(TemplateView):
    template_name = 'base/index.html'

    def get(self, request, *args, **kwargs):
        """
        Render the home page, ensuring latest messages and tagged messages are available for use in the template

        :param request: The current request
        :param args: sent to parent method
        :param kwargs: sent to parent method
        :return: Render the search message results page
        """

        latest_messages = Message.objects.order_by('-created').all()[:5]
        latest_tagged_messages = Message.objects.filter(message_text__icontains=' #').order_by('-created').all()[:5]

        context = self.get_context_data(**kwargs)
        context['latest_messages'] = latest_messages
        context['latest_tagged_messages'] = latest_tagged_messages
        return self.render_to_response(context)


def register(request):
    """
    Create a user using the information sent by a POST request. Perform backend validation on the email.
    Handle error messages for invalid email addresses and whether the username has already been taken

    :param request: The current request
    :return: Redirect the user to the appropriate page, with any necessary messages
    """
    username = request.POST.get('username')
    password = request.POST.get('password')
    email = request.POST.get('email')

    """
    Perform some backend validation
    """
    if not username:
        messages.error(request, 'Please enter a username', extra_tags='danger')
    elif len(username) > 150:
        messages.error(request, 'The maximum number of characters for a username is 150', extra_tags='danger')
    if not password:
        messages.error(request, 'Please enter a password', extra_tags='danger')
    if not email:
        messages.error(request, 'Please enter an email address', extra_tags='danger')
    elif len(email) > 254:
        messages.error(request, 'The maximum number of characters for an email address is 254', extra_tags='danger')

    """
    If any of the backend validation has failed, redirect back to the sign in page
    TODO: Add functionality to refill the form with any data the user has input
    """
    if len(messages.get_messages(request)) != 0:
        return HttpResponseRedirect(reverse('base:signup'))

    try:
        validate_email(email)
    except ValidationError:
        messages.error(request, 'Please enter a valid email address', extra_tags='danger')
        return HttpResponseRedirect(reverse('base:signup'))

    try:
        user = User.objects.create_user(username, email, password)
    except IntegrityError:
        messages.error(request, 'That username already exists', extra_tags='danger')
        return HttpResponseRedirect(reverse('base:signup'))
    except ValueError:
        messages.error(request, 'Please ensure you have entered a username, email, and password', extra_tags='danger')
        return HttpResponseRedirect(reverse('base:signup'))
    except DatabaseError:
        messages.error(request, 'Error creating message, please contact support', extra_tags='danger')
        return HttpResponseRedirect(reverse('wire_profile:current_profile'))

    login(request, user)
    messages.success(request, 'Welcome to Wire, ' + user.username)
    return HttpResponseRedirect(reverse('base:home'))


def verify_user(request):
    """
    Validate the username and password provided by the request

    :param request: The request that called this function
    :return: If the username and password is valid, log the user in and redirect to the home page. Else, redirect the
             user to the log in page and show an error message
    """
    username = request.POST.get('username')
    password = request.POST.get('password')

    """
    Perform some backend validation
    """
    if not username:
        messages.error(request, 'Please enter a username', extra_tags='danger')
    elif len(username) > 150:
        messages.error(request, 'The maximum number of characters for a username is 150', extra_tags='danger')
    if not password:
        messages.error(request, 'Please enter a password', extra_tags='danger')

    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        messages.success(request, 'Welcome back, ' + user.username)
        return HttpResponseRedirect(reverse('base:home'))
    else:
        messages.error(request, 'Your username or password is incorrect', extra_tags='danger')
        return HttpResponseRedirect(reverse('base:login'))


def log_out(request):
    """
    Log the user out of the current session

    :param request: The request that called this function
    :return: Log the user out and return to the home page
    """
    logout(request)
    messages.success(request, 'You have logged out successfully')
    return HttpResponseRedirect(reverse('base:home'))


def recommended_users(request, excluded_username):
    """
    Return five users that is not the logged in user, anyone followed by the logged in user, or the specified excluded
    user

    :param request: The request that called this function
    :param excluded_username: A user not to include in the list
    :return: JSON list of users
    """
    try:
        if request.user.is_authenticated:
            follow_query = Follow.objects.filter(follower_id=request.user)
            users = User.objects.filter().exclude(id=request.user.id).exclude(username=excluded_username)\
                .exclude(followed_user__in=follow_query).values('username')[:5]
            return JsonResponse(list(users), safe=False)

        users = User.objects.filter().exclude(username=excluded_username).values('username')[:5]
        return JsonResponse(list(users), safe=False)

    except (ObjectDoesNotExist, FieldDoesNotExist):
        messages.error(request, 'Error retrieving recommended users. Please Contact IT', extra_tags='danger')
        return HttpResponseRedirect(reverse('base:home'))

django/wire/base/templates/base/index.html
{% extends "base/global/base.html" %}

{% load static %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'base/home.js'%}"></script>
{% endblock %}

{% block content %}
    <header class="jumbotron jumbotron-fluid bg-dark text-light">
        <div class="container">
            <h1 class="text-center">What's going on?</h1>
        </div>
    </header>
    <main>
        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                    <h1>Latest Wires</h1>
                    <ul id="latest-messages" class="messages-list list-group">
                    {% for message in latest_messages %}
                        <li class="list-group-item">
                            <h4 class="list-group-item-heading">
                                {{ message.message_text }}
                            </h4>
                            <p class="list-group-item-text">
                                Posted on {{ message.created|date:"d/m/Y" }} at {{ message.created|date:"G:i" }} by <a href="/profile/{{ message.user.username }}">{{ message.user.username }}</a>
                            </p>
                        </li>
                    {% empty %}
                        <h3>No one has created a Wire yet</h3>
                    {% endfor %}
                    </ul>
                </div>
                <div class="col-sm-4">
                    <h1>Latest Tagged Wires</h1>
                    <ul id="latest-tagged-messages" class="messages-list list-group">
                        {% for message in latest_tagged_messages %}
                            <li class="list-group-item">
                                <h4 class="list-group-item-heading">
                                    {{ message.message_text }}
                                </h4>
                                <p class="list-group-item-text">
                                    Posted on {{ message.created|date:"d/m/Y" }} at {{ message.created|date:"G:i" }} by <a href="/profile/{{ message.user.username }}">{{ message.user.username }}</a>
                                </p>
                            </li>
                        {% empty %}
                            <h3>No one has created a Tagged Wire yet</h3>
                        {% endfor %}
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

django/wire/base/templates/base/login.html
{% extends "base/global/base.html" %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Login" "base:login" %}
{% endblock %}

{% block title %}
    Login
{% endblock %}

{% block content %}
    <main class="jumbotron">
        <div class="container">
            <div class="row">
                <h2 class="join-msg text-center col-sm-12">Login</h2>
            </div>
            <div class="row">
                <form action="{% url 'base:verify' %}" method="POST" class="col-sm-12 form-horizontal">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="col-sm-12">
                            <input type="text" class="form-control" name="username" placeholder="Username" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <input type="password" class="form-control" name="password" placeholder="Password" />
                        </div>
                    </div>
                    <div class="col-sm-12 text-center">
                        <button type="submit" class="btn btn-primary col-sm-12">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </main>
{% endblock %}

django/wire/base/templates/base/signup.html
{% extends "base/global/base.html" %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Signup" "base:signup" %}
{% endblock %}

{% block title %}
    Signup
{% endblock %}


{% block content %}
    <main class="jumbotron">
        <div class="container">
            <div class="row">
                <h2 class="join-msg text-center col-sm-12">Join Wire Today</h2>
            </div>
            <div class="row">
                <form action="{% url 'base:register' %}" method="POST" class="col-sm-12 form-horizontal">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="col-sm-12">
                            <input type="text" class="form-control" required="true" name="username" placeholder="Username" maxlength="150" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <input type="email" class="form-control" required="true" name="email" placeholder="Email" maxlength="254" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <input type="password" class="form-control" required="true" name="password" placeholder="Password" />
                        </div>
                    </div>
                    <div class="col-sm-12 text-center">
                        <button type="submit" class="btn btn-primary col-sm-12">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </main>
{% endblock %}